name: datapipes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch
  - rioxarray
  - torchdata
  - torchvision
  - xarray
  - fsspec
  - zarr
pip:
  - einops
  - pathy
  - git+https://github.com/SheffieldSolar/PV_Live-API
  - pyaml_env
  - nowcasting_datamodel
